# Generated by Django 3.2.25 on 2024-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_folder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
